const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const Accounts = require('../lib/accounts');

test('contas: migração, hash, troca própria, mestre, sessões e persistência', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'marco-accounts-'));
  Object.assign(process.env, { DATA_DIR: dir, NODE_ENV: 'development', ADMIN_USER: 'admin-original', ADMIN_PASSWORD: 'original-password', MASTER_USER: 'dono-mestre', MASTER_PASSWORD: 'master-password-private' });
  const express = require('express'); const app = express(); app.use(express.json());
  require('../lib/admin')(app, []);
  const server = app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
  t.after(async () => { await new Promise(r => server.close(r)); await fs.rm(dir, { recursive: true, force: true }); });
  const base = 'http://127.0.0.1:' + server.address().port;
  const request = (url, body, cookie, extra = {}) => fetch(base + '/api/admin/' + url, { ...(body ? { method: 'POST', body: JSON.stringify(body) } : {}),
    headers: { 'Content-Type': 'application/json', 'X-Loja-Request': '1', ...(cookie ? { Cookie: cookie } : {}), ...extra } });
  const login = async (usuario, senha) => { const response = await request('login', { usuario, senha }); assert.equal(response.status, 200); return response.headers.get('set-cookie').split(';')[0]; };
  const admin = await login('admin-original', 'original-password');
  const other = await login('admin-original', 'original-password');
  const master = await login('dono-mestre', 'master-password-private');
  const accountFile = path.join(dir, 'admin-account.json');
  const raw = await fs.readFile(accountFile, 'utf8');
  assert.ok(!raw.includes('original-password')); assert.ok(!raw.includes('master-password-private'));
  assert.equal((await request('conta')).status, 401);
  assert.equal((await fetch(base + '/data/admin-account.json')).status, 404);
  const info = await (await request('conta', null, admin)).json();
  assert.equal(info.role, 'admin'); assert.equal(info.hash, undefined); assert.ok(!JSON.stringify(info).includes('dono-mestre'));
  const change = { usuario: 'admin-novo', senhaAtual: 'original-password', novaSenha: 'new-password-long', confirmacao: 'new-password-long' };
  assert.equal((await request('conta', change, admin, { Origin: 'https://evil.example' })).status, 403);
  assert.equal((await request('conta', { ...change, usuario: 'dono-mestre' }, admin)).status, 400);
  assert.equal((await request('conta', { ...change, senhaAtual: 'wrong' }, admin)).status, 400);
  assert.equal((await request('conta', change, admin)).status, 200);
  assert.equal((await request('pedidos', null, admin)).status, 401);
  assert.equal((await request('pedidos', null, other)).status, 401);
  assert.equal((await request('pedidos', null, master)).status, 200);
  assert.equal((await request('login', { usuario: 'admin-original', senha: 'original-password' })).status, 401);
  const newAdmin = await login('admin-novo', 'new-password-long');
  assert.ok(await new Accounts(dir).authenticate('admin-novo', 'new-password-long'));
  assert.equal(await new Accounts(dir).authenticate('admin-original', 'original-password'), null);
  const reset = { usuario: 'admin-recuperado', senhaAtual: 'master-password-private', novaSenha: 'reset-password-long', confirmacao: 'reset-password-long' };
  assert.equal((await request('conta', reset, newAdmin)).status, 400);
  assert.equal((await request('conta', reset, master)).status, 200);
  assert.equal((await request('pedidos', null, newAdmin)).status, 401);
  assert.equal((await request('conta', null, master)).status, 200);
  await login('admin-recuperado', 'reset-password-long');
  const accounts = new Accounts(dir);
  const identity = await accounts.authenticate('admin-recuperado', 'reset-password-long');
  accounts.writer.atomicWrite = async () => { throw new Error('Disk failure'); };
  await assert.rejects(accounts.change(identity, { ...reset, senhaAtual: 'reset-password-long' }));
  assert.ok(await accounts.authenticate('admin-recuperado', 'reset-password-long'));
  await fs.writeFile(accountFile, '{invalid');
  await assert.rejects(new Accounts(dir).authenticate('admin-original', 'original-password'));
  assert.equal(await fs.readFile(accountFile, 'utf8'), '{invalid');
});
