const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const ProductStore = require('../lib/product-store');
const seed = require('../public/produtos.json');
test('catálogo: migração, concorrência, revisões, exclusão, backup e corrupção', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'catalog-store-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const store = new ProductStore(dir, seed);
  const original = await store.list();
  assert.deepEqual(JSON.parse(await fs.readFile(path.join(dir, 'produtos.json'), 'utf8')), original);
  assert.equal(original.length, seed.length);
  assert.equal(original[0].imagens.length, 5); assert.equal(original[0].imagens[0], seed[0].imagem);
  const saved = await Promise.all(Array.from({ length: 8 }, (_, i) => store.save({ ...original[0], nome: 'Produto ' + i })));
  assert.equal(new Set(saved.map(p => p.id)).size, 8);
  assert.equal((await new ProductStore(dir, seed).list()).length, 10);
  const updated = await store.save({ ...original[0], nome: 'Alterado', imagens: [...original[0].imagens].reverse() }, 1);
  assert.equal(updated.revisao, 2); assert.equal(updated.imagem, original[0].imagens[4]);
  await assert.rejects(store.save(original[0], 1), { status: 409 });
  await store.save({ revisao: 2 }, 1, true);
  assert.equal((await store.list()).length, 9);
  const recreated = await store.save(original[0]); assert.equal(recreated.id, 11);
  assert.equal(JSON.parse(await fs.readFile(path.join(dir, 'produtos.json.bak'))).length, 10);
  await fs.writeFile(path.join(dir, 'produtos.json'), '{broken');
  await assert.rejects(store.save(original[0]));
  assert.equal(await fs.readFile(path.join(dir, 'produtos.json'), 'utf8'), '{broken');
});
test('HTTP: produtos autenticados, upload, dados públicos, validação, reinício e payload SuperFrete', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'catalog-http-'));
  let shippingPayload;
  const carrier = http.createServer(async (req, res) => {
    let body = ''; for await (const part of req) body += part;
    shippingPayload = JSON.parse(body); assert.equal(req.headers.authorization, 'Bearer test-only-token');
    res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify([{ id: 1, name: 'Teste', price: 22, delivery_time: 3 }]));
  }).listen(0, '127.0.0.1');
  await new Promise(r => carrier.once('listening', r));
  Object.assign(process.env, { DATA_DIR: dir, ADMIN_USER: 'teste', ADMIN_PASSWORD: 'teste-password-only', NODE_ENV: 'development', DEMO_MODE: 'false', SUPERFRETE_TOKEN: 'test-only-token', CEP_ORIGEM: '88370603', SUPERFRETE_API_URL: `http://127.0.0.1:${carrier.address().port}` });
  let app = require('../server'); let server = app.listen(0, '127.0.0.1');
  await new Promise(r => server.once('listening', r));
  t.after(async () => { await new Promise(r => server.close(r)); await new Promise(r => carrier.close(r)); await fs.rm(dir, { recursive: true, force: true }); });
  let base = `http://127.0.0.1:${server.address().port}`;
  const request = (url, body, auth = {}) => fetch(base + url, { ...(body ? { method: 'POST', body: JSON.stringify(body) } : {}), headers: { 'Content-Type': 'application/json', 'X-Loja-Request': '1', ...auth } });
  const login = await request('/api/admin/login', { usuario: 'teste', senha: 'teste-password-only' });
  const auth = { Cookie: login.headers.get('set-cookie').split(';')[0] };
  const original = (await (await request('/api/produtos')).json())[0];
  for (const route of ['/api/admin/produtos', '/api/admin/produtos/1', '/api/admin/produtos/1/excluir', '/api/admin/imagens']) assert.equal((await request(route, original)).status, 401);
  assert.equal((await request('/api/admin/produtos', original, { ...auth, Origin: 'https://evil.example' })).status, 403);
  for (const field of ['preco', 'largura', 'comprimento', 'altura', 'peso']) {
    for (const invalid of [-1, 0, null, '', '2', 1000001, 0.00001]) assert.equal((await request('/api/admin/produtos', { ...original, [field]: invalid }, auth)).status, 400, field + ': ' + invalid);
  }
  for (const imagens of [[], ['javascript:alert(1)'], ['imagens/../.env'], Array(21).fill(original.imagem)]) assert.equal((await request('/api/admin/produtos', { ...original, imagens }, auth)).status, 400);
  assert.equal((await request('/api/admin/imagens', { imagem: 'data:image/png;base64,PHNjcmlwdD4=' }, auth)).status, 400);
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aG1sAAAAASUVORK5CYII=';
  const upload = await request('/api/admin/imagens', { imagem: 'data:image/png;base64,' + png }, auth);
  assert.equal(upload.status, 201); const image = (await upload.json()).imagem;
  assert.equal((await request(image)).status, 200);
  const created = await request('/api/admin/produtos', { ...original, nome: '<b>Produto novo</b>', preco: 25.5, peso: 0.3, largura: 11, comprimento: 21, altura: 4, imagens: [image, original.imagem] }, auth);
  assert.equal(created.status, 201); const product = await created.json();
  let catalog = await (await request('/produtos.json')).json(); assert.equal(catalog.length, 3);
  assert.equal(catalog[2].imagens.length, 2);
  const edit = await request('/api/admin/produtos/' + product.id, { ...product, descricao: 'Nova descrição', preco: 30, imagens: [original.imagem, image] }, auth);
  assert.equal(edit.status, 200);
  const freight = await request('/api/frete', { cep: '01001000', itens: [{ id: product.id, quantidade: 3 }, { id: 2, quantidade: 2 }], peso: 0.001, valor: 0 });
  assert.equal(freight.status, 200);
  assert.deepEqual(shippingPayload.package, { weight: 2.3, height: 36, width: 18, length: 24 });
  assert.equal(shippingPayload.options.insurance_value, 329.8);
  for (const itens of [[], [{ id: 999, quantidade: 1 }], [{ id: 1, quantidade: 0 }], [{ id: 1, quantidade: 1 }, { id: 1, quantidade: 1 }]]) assert.equal((await request('/api/frete', { cep: '01001000', itens })).status, 400);
  const js = await (await request('/produtos.js')).text(); assert.ok(js.includes('\\u003cb>')); assert.ok(!js.includes('test-only-token'));
  await new Promise(r => server.close(r)); delete require.cache[require.resolve('../server')]; app = require('../server'); server = app.listen(0, '127.0.0.1');
  await new Promise(r => server.once('listening', r)); base = `http://127.0.0.1:${server.address().port}`;
  catalog = await (await request('/api/produtos')).json(); assert.equal(catalog[2].preco, 30); assert.equal(catalog[2].imagem, original.imagem);
  assert.equal((await request(image)).status, 200);
  assert.equal((await request('/api/admin/produtos', null, auth)).status, 401);
});
